# Generated by Django 5.0.6 on 2024-06-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stickynote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('sets', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('description', models.TextField()),
                ('creator', models.CharField(max_length=30)),
            ],
        ),
    ]
